### ISSUE TITLE
Get the decomposed gates

### ISSUE THREAD

**Issue by Mushkan-Sureka** [clementsw/interferometer#1]
Hi! I am trying to get the decomposed beam splitter and rotation gate from the algorithm. Essentially I am trying to connect my vacuum states in the interferometer. How do I do it?

**Comment by clementsw** [comment]
Hi! Sorry, after a long absence I've finally gotten back to this. In case this can still be useful, once you've decomposed a unitary matrix and have your interferometer instance I, all the beam splitters and their settings are stored as a list that you can access with I.BS_list. This is now illustrated in the brand new tutorial notebook.
